// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using patient.Models;

namespace patient.Migrations
{
    [DbContext(typeof(PatientContext))]
    [Migration("20201021114648_FirstCreate")]
    partial class FirstCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("patient.Models.Patient", b =>
                {
                    b.Property<int>("patient_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DOB");

                    b.Property<string>("address");

                    b.Property<string>("appointment_date");

                    b.Property<string>("appointment_time");

                    b.Property<string>("contact");

                    b.Property<string>("diagnosis_reason");

                    b.Property<string>("doctor_name");

                    b.Property<string>("email");

                    b.Property<string>("patient_name");

                    b.HasKey("patient_id");

                    b.ToTable("patients");
                });
#pragma warning restore 612, 618
        }
    }
}
